#This is workflow name
name: Hello

#runs on a trigger
on:
  push:
    branches: [main]

  #These are jobs inside the workflow
jobs:
  
  #this is the name of the job
    greet:
      #this is github runner
      runs-on: Ubuntu-latest
      steps:
        - name: say hello to user
          run: echo "Hello Pallavi"

        - name: say hello to username
          run: echo "Hello $USER"
